spring:
  application:
    name: UberLocationService
  data:
    redis:
      host: localhost
      port: 6379
  cache:
    type: redis

server:
  port: 3004

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

redis:
  port: 6379
  host: localhost